### ISSUE TITLE
Archive cncf/foundation-starter-kit

### ISSUE THREAD

**Issue by nate-double-u** [cncf/foundation-starter-kit#2]
- [x] Edit readme 
- [x] Add link to https://github.com/cncf/dot-org-hugo-theme/
- [x] Archive repo

context: https://cloud-native.slack.com/archives/CUJ6W5TLM/p1698675363548579

**Comment by chalin** [comment]
Unless you've started working on this, you can assign it to me @nate-double-u. Do you have the necessary permissions to archive the repo?

**Comment by krook** [comment]
I can archive once you're done @chalin

**Comment by krook** [comment]
Done
